Favorite button & Return button
Canato/mentoria-edu pull request #8
Opened 2023-11-30 03:12 UTC by brigidoeduardo

Details Activity Return Button Set (xml + finish)
Details Activity Favorite Button Toggle Set (xml + drawables)

2023-12-13 15:02 UTC, Canato requested changes
Good PR

2023-12-14 15:20 UTC, brigidoeduardo commented on app/build.gradle
> +    implementation 'androidx.room:room-ktx:2.6.1'
Done

2023-12-14 15:21 UTC, brigidoeduardo commented on app/src/main/java/com/monzo/androidtest/articledetails/data/ArticleDetailsRepository.kt
> +        private const val KEY_FAVORITE_ARTICLES = "favorite_articles"
Done

2023-12-14 15:22 UTC, brigidoeduardo commented on app/src/main/java/com/monzo/androidtest/articledetails/presentation/ArticleDetailsViewModel.kt
> +    val articleUrl: String
The private was greyed out, so I removed it, in the new IDE is back to being highlighted, all good

2023-12-14 15:28 UTC, brigidoeduardo commented on app/src/main/java/com/monzo/androidtest/articledetails/data/ArticleDetailsRepository.kt
> +        return sharedPreferences.all.keys.filter { it.startsWith(KEY_FAVORITE_STATE_PREFIX) }
Done

2023-12-14 15:46 UTC, brigidoeduardo commented on app/src/main/java/com/monzo/androidtest/articledetails/data/ArticleDetailsRepository.kt
> +    }
Done

2023-12-14 16:10 UTC, Canato approved these changes

2023-12-14 16:10 UTC, merged